version: '3'

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: confluent
      MYSQL_DATABASE: root
      MYSQL_DATABASE: ksql_poc
    ports:
      - 3306:3306
    command: --server-id=1 --log-bin=mysql-bin --binlog-format=row --binlog-row-image=full

  db-population:
    image: adoptopenjdk:11-jre-hotspot
    volumes:
      - ~/.m2:/root/.m2
      - ./db-population:/db-population
    working_dir: /db-population
    command: ./mvnw liquibase:update


  zookeeper:
    image: confluentinc/cp-zookeeper:5.4.1
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: "2181"
      ZOOKEEPER_TICK_TIME: "2000"

  kafka:
    image: confluentinc/cp-kafka:5.4.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - 9093:9093
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT1:PLAINTEXT,PLAINTEXT2:PLAINTEXT"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT1://localhost:9093,PLAINTEXT2://kafka:9092"
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT2
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  sr:
    image: confluentinc/cp-schema-registry:5.4.1
    depends_on:
      - kafka
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: "kafka:9092"
      SCHEMA_REGISTRY_KAFKASTORE_TOPIC_REPLICATION_FACTOR: 1
      SCHEMA_REGISTRY_HOST_NAME: "sr"
    ports:
      - 8081:8081

  debezium:
    container_name: debezium
    depends_on:
      - mysql
      - kafka
    build:
      context: debezium
    volumes:
      - ./debezium/conf:/conf
      - ./debezium/conf/debezium-standalone-local.properties:/conf/cc.properties
    ports:
      - 8083:8083
    command: /usr/bin/connect-standalone /conf/debezium-standalone-local.properties /conf/mysql-connector-local.properties /conf/jdbc-sink.properties
#    command: /usr/bin/connect-standalone /conf/debezium-standalone-local.properties /conf/mysql-connector-local.properties

  ksqldb-server:
    image: confluentinc/ksqldb-server:0.7.1
#    image: confluentinc/ksqldb-server:0.6.0
    hostname: ksqldb-server
    container_name: ksqldb-server
    depends_on:
      - kafka
      - sr
    ports:
      - "8088:8088"
    environment:
      KSQL_LISTENERS: http://0.0.0.0:8088
      KSQL_BOOTSTRAP_SERVERS: kafka:9092
      KSQL_KSQL_INTERNAL_TOPIC_REPLICAS: 1
      KSQL_KSQL_SINK_REPLICAS: 1
      KSQL_KSQL_STREAMS_REPLICATION_FACTOR: 1
      KSQL_KSQL_LOGGING_PROCESSING_TOPIC_REPLICATION_FACTOR: 1
      KSQL_KSQL_LOGGING_PROCESSING_STREAM_AUTO_CREATE: "true"
      KSQL_KSQL_LOGGING_PROCESSING_TOPIC_AUTO_CREATE: "true"
      KSQL_KSQL_SCHEMA_REGISTRY.URL: "http://sr:8081"
#      KSQL_KSQL_QUERIES_FILE: "/conf/init.ksql"
    volumes:
      - ./:/conf

  ksqldb-cli:
    image: confluentinc/ksqldb-cli:0.7.1
    container_name: ksqldb-cli
    depends_on:
      - ksqldb-server
    entrypoint: /bin/sh
    tty: true

